#:kivy 1.0
<MenuLayout>:
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Line:
            width: 2.
            rectangle: self.x, self.y, self.width, self.height
        #Rectangle:
            #pos: self.x, self.y
            #size: (self.width, self.height*1)


# <MenuOption>:
#     canvas.before:
#         Color:
#             rgba: (1,1,1,1)
#         Rectangle:
#             pos: self.x, self.y
#             size: self.width, self.height
